project:
  type: website
  output-dir: _site

website:
  title: Open Science Impact Indicator Handbook
  reader-mode: true

  site-url: https://handbook.pathos-project.eu/
  repo-url: https://github.com/PathOS-project/indicator_handbook/
  repo-branch: main
  repo-actions: [edit, issue]

  navbar:
    search: true
    left:
    - text: "Causality"
      href: sections/0_causality/causal_intro/article/intro-causality.qmd
    - text: "Open Science"
      href: sections/1_open_science/introduction_open_science.qmd
    - text: "Academic Impact"
      href: sections/2_academic_impact/introduction_academic_impact.qmd
    - text: "Societal Impact"
      href: sections/3_societal_impact/introduction_societal_impact.qmd
    - text: "Economic Impact"
      href: sections/4_economic_impact/introduction_economic_impact.qmd
    - text: "Reproducibility"
      href: sections/5_reproducibility/introduction_reproducibility.qmd

    tools:
      - icon: github
        href:  https://github.com/PathOS-project/indicator_handbook/

  sidebar:

    - title: Home
      contents:
        - index.qmd

    - title: Causality
      contents:
        - sections/0_causality/causal_intro/article/intro-causality.qmd
        - sections/0_causality/open_data_citation_advantage.qmd
        - sections/0_causality/social_causality.qmd
        - sections/0_causality/open_data_cost_savings.qmd

    - title: Open Science
      contents:
        - section: Open Science
          contents:
            - sections/1_open_science/introduction_open_science.qmd
            - sections/1_open_science/APC_costs.qmd
            - sections/1_open_science/availability_data_repositories.qmd
            - sections/1_open_science/availability_preprint_repositories.qmd
            - sections/1_open_science/availability_publication_repositories.qmd
            - sections/1_open_science/citizen_science.qmd
            - sections/1_open_science/deposition_open_metadata.qmd
            - sections/1_open_science/evaluation_open_science_in_research_assessment.qmd
            - sections/1_open_science/open_access_journals.qmd
            - sections/1_open_science/prevalence_open_access_publishing.qmd
            - sections/1_open_science/prevalence_national_open_science_policies.qmd
            - sections/1_open_science/prevalence_open_fair_data_practices.qmd
            - sections/1_open_science/prevalence_open_method_practices.qmd
            - sections/1_open_science/prevalence_open_peer_review.qmd
            - sections/1_open_science/prevalence_open_science_funding_policies.qmd
            - sections/1_open_science/prevalence_OS_training_support.qmd
            - sections/1_open_science/prevalence_preprinting.qmd
            - sections/1_open_science/prevalence_replication_studies.qmd
            - sections/1_open_science/transformative_publishing_agreements.qmd

    - title: Academic Impact
      contents:
        - section: Academic Impact
          contents:
            - sections/2_academic_impact/introduction_academic_impact.qmd
            - sections/2_academic_impact/academic_readership.qmd
            - sections/2_academic_impact/citation_impact.qmd
            - sections/2_academic_impact/collaboration_intensity.qmd
            - sections/2_academic_impact/diversity.qmd
            - sections/2_academic_impact/extra-academic_collaboration.qmd
            - sections/2_academic_impact/interdisciplinarity_novelty.qmd
            - sections/2_academic_impact/quality.qmd
            - sections/2_academic_impact/use_of_code_in_research.qmd
            - sections/2_academic_impact/use_of_data_in_research.qmd
            - sections/2_academic_impact/thematic_persistence.qmd

    - title: Societal Impact
      contents:
        - section: Societal Impact
          contents:
            - sections/3_societal_impact/introduction_societal_impact.qmd
            - sections/3_societal_impact/uptake_and_impact_on_societal_issues.qmd
            - sections/3_societal_impact/uptake_by_media.qmd
            - sections/3_societal_impact/scientific_literacy.qmd
            - sections/3_societal_impact/uptake_by_policy_makers.qmd
            - sections/3_societal_impact/uptake_by_patient_groups.qmd
            - sections/3_societal_impact/uptake_in_education.qmd
            - sections/3_societal_impact/uptake_in_medical_practice.qmd
            - sections/3_societal_impact/uptake_in_the_legal_sector.qmd
            - sections/3_societal_impact/OS_access_advantage.qmd

    - title: Economic Impact
      contents:
        - section: Economic Impact
          contents:
            - sections/4_economic_impact/introduction_economic_impact.qmd
            - sections/4_economic_impact/science_industry_collaboration.qmd
            - sections/4_economic_impact/innovation_output.qmd
            - sections/4_economic_impact/socially_relevant_products_and_processes.qmd
            - sections/4_economic_impact/economic_growth_of_companies.qmd
            - sections/4_economic_impact/labour_market_impacts.qmd
            - sections/4_economic_impact/cost_savings.qmd

    - title: Reproducibility
      contents:
        - section: Reproducibility
          contents:
            - sections/5_reproducibility/introduction_reproducibility.qmd
            - sections/5_reproducibility/consistency_in_reported_numbers.qmd
            - sections/5_reproducibility/impact_of_open_code_in_research.qmd
            - sections/5_reproducibility/impact_of_open_data_in_research.qmd
            - sections/5_reproducibility/inclusion_in_systematic_reviews_or_meta-analyses.qmd
            - sections/5_reproducibility/level_of_replication.qmd
            - sections/5_reproducibility/polarity_of_publications.qmd
            - sections/5_reproducibility/reuse_of_code_in_research.qmd
            - sections/5_reproducibility/reuse_of_data_in_research.qmd

format:
  html:
    shift-heading-level-by: -1
    toc: true
    toc-expand: 2
    theme:
      - cosmo
      - theme/style.scss
    code-link: true
    grid:
      sidebar-width: 350px

    author-meta: "V.A. Traag, etc..."
    callout-appearance: simple

zotero: PathOS
bibliography: references.bib

license:
  text: >
    Open Science Impact Indicator Handbook © 2024 by PathOS is licensed under CC BY 4.0
  type: open-access
  url: https://creativecommons.org/licenses/by/4.0/
